name: Deploy Cron Job and Run Server

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: List Compiled Files (Debugging)
        run: ls -la dist/

      - name: Start Express Server
        run: nohup node dist/server.js &

      - name: Run cron job
        run: node dist/index.js
